PANDAS-

In [ ]:
import pandas as pd
a = [1,2,3,54]
v = pd.Series(a)
print(v) #it is like a column in table and hold 1d data

0     1
1     2
2     3
3    54
dtype: int64

In [ ]:
import pandas as pd
a = [1,2,3,54]
v = pd.Series(a)
print(v)
print(v[0])
print(v[3])

0     1
1     2
2     3
3    54
dtype: int64
1
54

In [ ]:
import pandas as pd
a = [1,2,3,54]
v = pd.Series(a,index=["a","b","c","d"])
print(v)
print(v["d"])

a     1
b     2
c     3
d    54
dtype: int64
54

In [ ]:
import pandas as pd
a = [1,3,54]
v = pd.Series(a,index=["d1","d2","d3"])
print(v)
print(v["d2"])

d1     1
d2     3
d3    54
dtype: int64
3

In [ ]:
import pandas as pd
burn_fat={"d1":500,"d2":550}
v = pd.Series(burn_fat)
print(v)
print(v["d2"])

d1    500
d2    550
dtype: int64
550

#DATAFRAMES- are usually multi dimensional tables

In [ ]:
import pandas as pd
data={'cal_burn':[500,300,700],
      "duration":[50,30,3],
      "abc":[1,2,3],
      "we":[3,3,3]}
v= pd.DataFrame(data)
print(v)

   cal_burn  duration  abc  we
0       500        50    1   3
1       300        30    2   3
2       700         3    3   3

In [ ]:
#csv file
import pandas as pd
df = pd.read_csv("/content/Book1.csv")
print(df)

    sno name  rno address  marks1  marks2  marks3
0     0    A   11  GNoida     100      50      60
1     1    B   12  GNoida     100      50      45
2     2    A   13  GNoida     100      50      67
3     3    B   14  GNoida     100      50       6
4     4    A   15  GNoida     100      50      70
5     5    B   16  GNoida     100      50      50
6     6    A   17  GNoida     100      50      60
7     7    B   18  GNoida     100      50      70
8     8    A   19  GNoida     100      50      80
9     9    B   20  GNoida     100      50      68
10   10    A   21  GNoida     100      50      70
11   11    B   22  GNoida     100      50      70
12   12    A   23  Gnoida     100      50      80

In [ ]:
#aggregate functions used for analysing the data
import pandas as pd
data=pd.DataFrame([[9,4,5,9,"a1"],[5,3,3,7,"a2"],[7,8,4,9,"a3"]],
      columns=["hindi","english","hindi","science","rollno"])
print(data)

   hindi  english  hindi  science rollno
0      9        4      5        9     a1
1      5        3      3        7     a2
2      7        8      4        9     a3

In [ ]:
df. describe()

            sno       rno  marks1  marks2     marks3
count  13.00000  13.00000    13.0    13.0  13.000000
mean    6.00000  17.00000   100.0    50.0  61.230769
std     3.89444   3.89444     0.0     0.0  19.438595
min     0.00000  11.00000   100.0    50.0   6.000000
25%     3.00000  14.00000   100.0    50.0  60.000000
50%     6.00000  17.00000   100.0    50.0  68.000000
75%     9.00000  20.00000   100.0    50.0  70.000000
max    12.00000  23.00000   100.0    50.0  80.000000

aggregation function-
...count()
...sum()
...mean()
...median()
...mode()
...std()
...var()

In [ ]:
data = {"Gender":['m','f','m','m','f'],"Height":[171,172,173,178,169]}
df_sample = pd.DataFrame(data)
print(df_sample)
df_sample.agg(["min","max","sum","count"])

  Gender  Height
0      m     171
1      f     172
2      m     173
3      m     178
4      f     169

      Gender  Height
min        f     169
max        m     178
sum    mfmmf     863
count      5       5

In [ ]:
import pandas as pd
df= pd.DataFrame([[9,4,8,9,1],[8,10,7,6,1],[7,6,8,5,2],[3,4,5,6,2]],columns=['maths','english','science','history','dept'])
print(df)
a = df.groupby('dept')
print(a)
a.first()

   maths  english  science  history  dept
0      9        4        8        9     1
1      8       10        7        6     1
2      7        6        8        5     2
3      3        4        5        6     2
<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7821263505b0>

      maths  english  science  history
dept
1         9        4        8        9
2         7        6        8        5

In [ ]:
import pandas as pd
df= pd.DataFrame([[9,4,8,9,1],[8,10,7,6,1],[7,6,8,5,2],[7,4,5,6,2]],columns=['maths','english','science','history','dept'])
print(df)
a = df.groupby('maths')
print(a)
a.first()

   maths  english  science  history  dept
0      9        4        8        9     1
1      8       10        7        6     1
2      7        6        8        5     2
3      7        4        5        6     2
<pandas.core.groupby.generic.DataFrameGroupBy object at 0x782126351690>

       english  science  history  dept
maths
7            6        8        5     2
8           10        7        6     1
9            4        8        9     1

In [ ]:
import pandas as pd
df= pd.DataFrame([[9,4,8,9,'ds'],[8,10,7,6,'ds'],[7,6,8,5,'ai'],[3,4,5,6,'ds']],columns=['maths','english','science','history','dept'])
print(df)
a = df.groupby('dept')
print(a)
a.first()

   maths  english  science  history dept
0      9        4        8        9   ds
1      8       10        7        6   ds
2      7        6        8        5   ai
3      3        4        5        6   ds
<pandas.core.groupby.generic.DataFrameGroupBy object at 0x782126351b40>

      maths  english  science  history
dept
ai        7        6        8        5
ds        9        4        8        9

In [ ]:
import pandas as pd
df= pd.DataFrame([[9,4,8,9,'ds'],[8,10,7,6,'ds'],[7,6,8,5,'ai'],[3,4,5,6,'ai']],columns=['maths','english','science','history','dept'])
print(df)
print(df.sum())
a = df.groupby('dept').sum()
print(a)

   maths  english  science  history dept
0      9        4        8        9   ds
1      8       10        7        6   ds
2      7        6        8        5   ai
3      3        4        5        6   ai
maths            27
english          24
science          28
history          26
dept       dsdsaiai
dtype: object
      maths  english  science  history
dept
ai       10       10       13       11
ds       17       14       15       15

In [ ]:
import pandas as pd
df= pd.DataFrame([[9,4,8,9,'ds'],[8,10,7,6,'ds'],[7,6,8,5,'ai'],[3,4,5,6,'ds']],columns=['maths','english','science','history','dept'])
print(df)
a = df.groupby('science')
print(a)
a.first()

   maths  english  science  history dept
0      9        4        8        9   ds
1      8       10        7        6   ds
2      7        6        8        5   ai
3      3        4        5        6   ds
<pandas.core.groupby.generic.DataFrameGroupBy object at 0x78212789c730>

         maths  english  history dept
science
5            3        4        6   ds
7            8       10        6   ds
8            9        4        9   ds

In [ ]:
import pandas as pd
df= pd.DataFrame([[9,4,8,9,'ds'],[8,10,7,6,'ds'],[7,6,8,5,'ai'],[3,4,5,6,'ds']],columns=['maths','english','science','history','dept'])
print(df)
print(df.sum())
a = df.groupby('science').sum()
print(a)

   maths  english  science  history dept
0      9        4        8        9   ds
1      8       10        7        6   ds
2      7        6        8        5   ai
3      3        4        5        6   ds
maths            27
english          24
science          28
history          26
dept       dsdsaids
dtype: object
         maths  english  history  dept
science
5            3        4        6    ds
7            8       10        6    ds
8           16       10       14  dsai

In [ ]:
import pandas as pd
df= pd.DataFrame([[9,4,8,9,'ds'],[8,10,7,6,'ds'],[7,6,8,5,'ai'],[3,4,5,6,'ds']],columns=['maths','english','science','history','dept'])
print(df)
agg_functions = {'maths':['sum','mean','median','min','prod','max']}
a = df.groupby(['dept']).agg(agg_functions)
print(a)

   maths  english  science  history dept
0      9        4        8        9   ds
1      8       10        7        6   ds
2      7        6        8        5   ai
3      3        4        5        6   ds
     maths
       sum      mean median min prod max
dept
ai       7  7.000000    7.0   7    7   7
ds      20  6.666667    8.0   3  216   9

In [ ]:
import pandas as pd
df= pd.DataFrame([[9,4,8,9,'ds'],[8,10,7,6,'ds'],[7,6,8,5,'ai'],[3,4,5,6,'ds']],columns=['maths','english','science','history','dept'])
print(df)
agg_functions = ['sum','mean','median','min','prod','max']
a = df.groupby(['dept']).agg(agg_functions)
print(a)

   maths  english  science  history dept
0      9        4        8        9   ds
1      8       10        7        6   ds
2      7        6        8        5   ai
3      3        4        5        6   ds
     maths                               english                  ... science  \
       sum      mean median min prod max     sum mean median min  ...  median
dept                                                              ...
ai       7  7.000000    7.0   7    7   7       6  6.0    6.0   6  ...     8.0
ds      20  6.666667    8.0   3  216   9      18  6.0    4.0   4  ...     7.0

                  history
     min prod max     sum mean median min prod max
dept
ai     8    8   8       5  5.0    5.0   5    5   5
ds     5  280   8      21  7.0    6.0   6  324   9

[2 rows x 24 columns]

In [ ]:
from pandas import Series,DataFrame
import pandas as pd
import numpy as np
ser_1 = Series([1,1,2,-3,-5,8,13])
ser_1

0     1
1     1
2     2
3    -3
4    -5
5     8
6    13
dtype: int64

In [ ]:
ser_2 = Series([1,1,2,-3,-5],index=['a','b','c','d','e'])
ser_2

a    1
b    1
c    2
d   -3
e   -5
dtype: int64

In [ ]:
ser_2[['c','a','b']]

c    2
a    1
b    1
dtype: int64

In [ ]:
ser_2[ser_2>0]

a    1
b    1
c    2
dtype: int64

In [ ]:
ser_2*3

a     3
b     3
c     6
d    -9
e   -15
dtype: int64

In [ ]:
import numpy as np
np.exp(ser_2)

a    2.718282
b    2.718282
c    7.389056
d    0.049787
e    0.006738
dtype: float64

In [ ]:
dict_1 = {"f":100,"g":200,"h":300}
ser_3 = Series(dict_1)
ser_3

f    100
g    200
h    300
dtype: int64

In [ ]:
index=['f','g','h','i']
ser_4= Series(dict_1,index=index)
ser_4

f    100.0
g    200.0
h    300.0
i      NaN
dtype: float64

In [ ]:
pd.isnull(ser_4)

f    False
g    False
h    False
i     True
dtype: bool

In [ ]:
ser_4.isnull()

f    False
g    False
h    False
i     True
dtype: bool

In [ ]:
ser_3+ser_4

f    200.0
g    400.0
h    600.0
i      NaN
dtype: float64

In [ ]:
ser_4.name = 'fghi'

In [ ]:
ser_4.index.name = 'label'

In [ ]:
ser_4

label
f    100.0
g    200.0
h    300.0
i      NaN
Name: fghi, dtype: float64

In [ ]:
ser_4.index = ['a','b','c','d']
ser_4

a    100.0
b    200.0
c    300.0
d      NaN
Name: fghi, dtype: float64

In [ ]:
data_1 = {'state':['VA','VA','VA','MD','MD'],
          'year':[2012,2013,2015,2016,2014],
          'pop':[5.0,5.1,5.2,4.0,4.1]}
df_1 = DataFrame(data_1)
df_1

NameError: name 'DataFrame' is not defined